### ISSUE TITLE
stage1 coreos not found

### ISSUE THREAD

**Issue by MattKetmo** [blablacar/dgr#129]
**dgr** should be able to load stage1 from `/usr/lib/rkt/stage1-images/stage1-coreos.aci`.

From [rkt docs](https://github.com/coreos/rkt/blob/2ef89c8b2d3448e3e7325846aabacb004c36e064/Documentation/build-configure.md#location-of-the-default-stage1-image):

> The default value of this parameter is `<libdir>/rkt/stage1-images`, where `<libdir>` is a distribution-specific place for storing arch-dependent files.

**Comment by n0rad** [comment]
v60 do not use coreos-stage1 anymore and have his own systemd version embedded
