### ISSUE TITLE
dgr: aci vs oci road map

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [blablacar/dgr#172]
it appears that `rkt` will abandon `aci` in favor of `oci` rather soon:
https://github.com/coreos/rkt/issues/2757
can you please share `dgr: aci vs oci` road map?

**Comment by n0rad** [comment]
The plan on our side is to follow **rkt** implementation. As soon as **rkt** will support **oci**, we will implement it.

At some point when **oci** will be implemented in **rkt** and **docker**, we will probably support building with and for both (like we did at the very beginning of dgr).

**Comment by Andrei-Pozolotin** [comment]
great, thank you for clarification. probably could mention your plan right from the start
https://github.com/blablacar/dgr/blob/master/README.md
for example:

### dgr is future-proof
Surely you have heard of [Open Container Initiative](https://coreos.com/blog/oci-image-specification.html). As soon as `rkt` will support `oci`, we will implement it as well.

**Comment by n0rad** [comment]
done

**Comment by Andrei-Pozolotin** [comment]
thank you
