### ISSUE TITLE
dgr push -> acserver

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [blablacar/dgr#174]
I can not push form dgr to acserver;
https://github.com/appc/acserver
1) is it supposed to work at all?
2) if yes, can you point to an example?

**Comment by n0rad** [comment]
Yes it's compatible with appc push spec

I have just updated the readme with a [push and run](https://github.com/blablacar/dgr#push-an-aci-and-run-from-repository) example

**Comment by Andrei-Pozolotin** [comment]
1) thank you. will test/verify/report on your example

2) what are your plans for https://github.com/blablacar/acserver
* pull back to the origin?
* maintain local fork for test/demo?
* maintain local fork for production?
* etc?

**Comment by n0rad** [comment]
We will add small features and switch to it for our production at some point.

I'm not sure yet how it will diverge from original, so they may not want it for a simple server.

**Comment by Andrei-Pozolotin** [comment]
great. may I suggest to keep your fork "surface-compatible" to the origin, 
and activate your modifications via extra `-flag` or `--flag` or options.

so, origin says:
```
Usage of /usr/bin/acserver:
acserver SERVER_NAME ACI_DIRECTORY TEMPLATE_DIRECTORY USERNAME PASSWORD
Flags:
  -https
        Whether or not to provide https URLs for meta discovery
  -port int
        The port to run the server on (default 3000)
  -pubkeys string
        Path to gpg public keys images will be signed with
```

modifications activation example:

1) you dropped TEMPLATE_DIRECTORY
* instead, lets keep TEMPLATE_DIRECTORY on command line, and:
* when TEMPLATE_DIRECTORY is present, use it
* when TEMPLATE_DIRECTORY is missing, use baked-in template

2) you relaxed signature requirement
https://github.com/blablacar/acserver/commit/15f36241c2ed22487fa59f93aa59755b3bc47363#diff-7ddfb3e035b42cd70649cc33393fe32cR416
* instead, lets keep it enforced by default
* and relax it with `--optional-signature` flag

this approach should also increase chances that origin will accept your pull request

**Comment by n0rad** [comment]
changes are done directly on appc/acserver now
