### ISSUE TITLE
Templating in *.yml happens before merge with TEMPLATER_OVERRIDE.

### ISSUE THREAD

**Issue by nyodas** [blablacar/dgr#181]
The templating specified in the attibutes/*.yml in a pod happens before the merge of $TEMPLATER_OVERRIDE and them.

in aci:
```
Users:
    bob: a
```

in pod:
```
AllowUsers: '{{range $i,$d := .sshd.Users}}{{$i}} {{end}}'
Users:
    healtcheck: a
```

in TEMPLATER_OVERRIDE
```
Users:
    yolo: a
```

rendered.
```
AllowUsers: "bob healthcheck"
```

Is it working as intended ?

**Comment by n0rad** [comment]
nop,

Nice catch. I will fix it

**Comment by n0rad** [comment]
fixed in v72
