### ISSUE TITLE
Display aci name + version after build

### ISSUE THREAD

**Issue by MattKetmo** [blablacar/dgr#183]
Once the build is finished `dgr` should display the name + version of the built ACI (this would improve user experience especially when the version is dynamically generated via a template var).

It should work also for (clean) install/push.

**Comment by MattKetmo** [comment]
(Bonus) the output of dgr build should redirect to stderr while the display of the aci version at the end uses stdout (like the `rkt prepare` command which only outputs the pod uuid to stdout). So it would be easier to integrate it within a script (eg. `ACI=$(dgr build)`)

**Comment by n0rad** [comment]
ACI=$(dgr build) is not doable because build include user printing stuff. but I can output the aci-name:version to a file in target/

**Comment by n0rad** [comment]
done in v73
