### ISSUE TITLE
does dgr support local dependencies?

### ISSUE THREAD

**Issue by biax** [blablacar/dgr#204]
coming from acbuild -- i couldn't use a local aci dependency to build myapp

 would like to know if dgr is able to do this.

what im trying to do is have my-own-alpine-brew-base.aci as dependency for "myapps"

**Comment by n0rad** [comment]
All the dependencies mechanism, even during the build, is resolved by rkt so it should work.

Can you give us more context of what is going on ?

**Comment by biax** [comment]
after using dgr for the first time, i THINK i understand it a little bit better now.
