### ISSUE TITLE
Be able to dgr try into a pod

### ISSUE THREAD

**Issue by hightoxicity** [blablacar/dgr#209]
It would be really great to have the ability to run dgr try into a pod to test template rendering very fast.

Great thanks !

**Comment by f0** [comment]
@hightoxicity  does it not work?

**Comment by hightoxicity** [comment]
As far I know, I can do it for an aci, but not for a pod, maybe I am wrong, do I am?

**Comment by n0rad** [comment]
It's running each pod's aci tests individually. is it enough or do you need some pod context ?

**Comment by n0rad** [comment]
hum sorry, I was thinking about tests. try is not implemented for pod.
As a first step, I can reproduce what I just said about tests. It will probably meet your needs.

**Comment by n0rad** [comment]
fixed in v78
