### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by erikvanoosten** [blablacar/dgr#229]
Installation instructions seem to be missing. Can those be added please?

**Comment by n0rad** [comment]
There is nothing special to install, dgr is a single go binary, you just have to drop it in a bin directory (or not).

There is a configuration that is described [here](https://github.com/blablacar/dgr#configuration-file) if you want to configure special rkt access or push config.

What do you think is missing ?

**Comment by erikvanoosten** [comment]
Where does one obtain the binary?Op 1 feb. 2017 2:10 p.m. schreef Arnaud Lemaire <notifications@github.com>:There is nothing special to install, dgr is a single go binary, you just have to drop it in a bin directory (or not).
There is a configuration that is described here if you want to configure special rkt access or push config.
What do you think is missing ?

**Comment by n0rad** [comment]
oh, on github releases : https://github.com/blablacar/dgr/releases
