### ISSUE TITLE
Add example of using HTTP headers for dgr push authentication

### ISSUE THREAD

**Issue by fschr** [blablacar/dgr#261]
According to [this comment](https://github.com/blablacar/dgr/blob/master/dgr/push.go#L56),

```
	// SetHTTPHeaders is called on every request before being sent.
	// This is exposed so that the user of acpush can set any headers
	// necessary for authentication.
```

Can anyone provide an example of using custom authentication with `dgr push`?

**Comment by fschr** [comment]
[These lines of code](https://github.com/blablacar/dgr/blob/master/dgr/aci-push.go#L187-L207) led me to believe authentication is specified in rkt configuration files. You can read more [here](https://coreos.com/rkt/docs/latest/configuration.html). If I find a solution, I'll leave a comment here and close this issue.

**Comment by n0rad** [comment]
push.go is a copy of github.com/appc/acpush, I don't remember why we had to copy the code, probably a dependencies upgrade issue.

Using push with basic auth is describe in dgr readme. It was never tested with another method.

What kind of auth and server are you trying to use ?

**Comment by fschr** [comment]
@n0rad I would like to use GitLab's container registry service with a [personal access token](https://gitlab.com/help/user/profile/personal_access_tokens.md) (so I don't have to use Basic Auth or my username and password).

I need to pass my personal access token in as the "Private-Token" header when making requests.

If there isn't an easy way to do this, I'll just resort to Basic Auth as described in the readme.

**Comment by n0rad** [comment]
I'm not sure gitlab support the ACI format.
From https://gitlab.com/gitlab-org/gitlab-ce/issues/17784, I think it's not.

**Comment by fschr** [comment]
:cry: That's unfortunate.

Thanks for the help. I'll close this issue for now.
