### ISSUE TITLE
cnt should verify pushed dependencies when pushing

### ISSUE THREAD

**Issue by PrFalken** [blablacar/dgr#67]
Possibly a good idea to warn the users that they are pushing a version from which dependencies versions are not pushed yet.

example : 
- build base:42
- (forget to push base:42)
- build myAci:2 with a dependency on base:42
- push myAci:2
- cnt WARNs : myAci:2 depends on base:42 which does not appear on image repository.

It could be a simple warn or even refuse to push. That way nobody can run an image with missing deps.

**Comment by n0rad** [comment]
fixed in v57 since build require all dependencies
