### ISSUE TITLE
cnt test should support rkt 0.11

### ISSUE THREAD

**Issue by n0rad** [blablacar/dgr#74]
new version of rkt use private net by default. during test, we call services inside the container directly.
It was working previously because it uses host by default. now we have to parse the running container to get the private ip.

Current workaround is to use --net=host.

**Comment by nyodas** [comment]
add to the list the deprecated - - insecure-skip-verify flag

**Comment by n0rad** [comment]
will continue with --net=host until somebody open a new ticket
