### ISSUE TITLE
dependencies resolving

### ISSUE THREAD

**Issue by odolbeau** [blablacar/dgr#90]
Let's say we have an aci `aci.foobar.org/elasticsearch` which depends on `aci.foobar.org/java` (without any version constraint).
`cnt` try to reach `https://aci.foobar.org?ac-discovery=1` to retrieve existing versions.

In my case this domain doesn't existing as I don't need this discovery mechanism.

Is it possible to use `rkt` to retrieve the last local version of the wanted dependency?

**Comment by n0rad** [comment]
can you test if the latest version dgr is working now. It should be ok since examples are now integrated in the test suite and do no rely on remote repository

**Comment by odolbeau** [comment]
Seems OK right now, thanks. :+1:
